/*
-- Query: SELECT * FROM jupem18.dp_department
-- Date: 2022-03-08 11:29
*/
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (1,'Pejabat Ketua Pengarah Ukur Dan Pemetaan Malaysia','Office Of The Director General Of Survey And Mapping Malaysia',0,0,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (2,'Pejabat Timbalan Ketua Pengarah Ukur Dan Pemetaan I','Office Of The Deputy Director General Of Survey And Mapping I',0,1,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (3,'Pejabat Timbalan Ketua Pengarah Ukur Dan Pemetaan II','Office Of The Deputy Director General Of Survey And Mapping II',0,2,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (5,'Bahagian Dasar dan Penyelarasan Pemetaan','Coordinating and Mapping Policy Division',0,3,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (6,'Seksyen Dasar Pemetaan','Mapping Policy Section',5,4,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (7,'Seksyen Penyelarasan Pemetaan','Mapping Coordination Section',5,5,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (8,'Seksyen Pentadbiran Pemetaan','Mapping Administration Section',5,6,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (9,'Bahagian Kadaster','Cadastral Division',0,7,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (10,'Seksyen Pengurusan dan Pembangunan Kadaster','Cadastral Management and Development Section',9,9,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (11,'Seksyen Perundangan Kadaster','Cadastral Legislation Section',9,10,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (12,'Seksyen Naziran Kadaster','Cadastral Inspectorate Section  ',9,8,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (13,'Bahagian Geospatial Pertahanan','Defence Geospatial Division',0,11,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (14,'Seksyen Pembangunan Keupayaan Geospatial','Geospatial Capacity Development Section',13,12,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (15,'Markas Bahagian Geospatial Pertahanan','BGSP Headquarters',13,14,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (16,'Seksyen Pengurusan Maklumat Geospatial','Geospatial Information Management Section',13,15,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (17,'Seksyen Operasi Geospatial','Geospatial Operation Section',13,13,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (18,'Bahagian Ehwal Persempadanan','Boundary Affairs Division',0,17,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (19,'Seksyen Sempadan Darat Antarabangsa','International Land Boundary Section',18,18,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (20,'Seksyen Sempadan Negeri dan Penyelarasan','State Boundary and Coordinating Section',18,20,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (21,'Seksyen Sempadan Maritim Antarabangsa','International Maritime Boundary Section',18,19,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (22,'Bahagian Pangkalan Data Geospatial Negara','National Geospatial Database Division',0,21,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (25,'Seksyen Pengurusan Maklumat Dan Pembangunan Sistem','Data Management And System Development Section',22,25,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (26,'Seksyen Perkhidmatan Geospatial','Geospatial Services Section',22,24,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (27,'Seksyen Pembangunan Data Geospatial','Geospatial Data Development Section',22,23,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (28,'Seksyen Kawalan Kualiti','Quality Control Section',22,22,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (29,'Bahagian Kartografi dan GIS','Cartography and GIS Division',0,26,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (30,'Seksyen Penerbitan Peta Digital','Digital Map Publications Section',29,29,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (31,'Seksyen Data Geospatial','Geospatial Data Section',29,28,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (32,'Seksyen Percetakan','Printing Section',29,30,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (33,'Seksyen Pentadbiran dan Kewangan','Administration and Finance Section',29,27,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (34,'Bahagian Pemetaan Utiliti ','Utility Mapping Division',0,31,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (35,'Seksyen Naziran dan Pembangunan Pangkalan Data','Database Development and Inspectorate Section',34,32,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (36,'Seksyen Penyelarasan dan Pentadbiran','Coordination and Administration Section  ',34,33,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (37,'Bahagian Ukur Geodetik','Geodetic Survey Division',0,34,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (38,'Seksyen Graviti dan Falak','Gravity and Islamic Astronomy Section',37,35,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (39,'Seksyen Infrastruktur Rujukan Tegak','Vertical Reference Infrastructure Section',37,37,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (40,'Seksyen Infrastruktur Rujukan Spatial','Spatial Reference Infrastructure Section',37,36,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (41,'Seksyen Perkhidmatan dan Penyelarasan','Services and Coordinating Section',37,38,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (42,'Bahagian Perancangan dan Korporat','Planning and Corporate Division',0,39,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (43,'Seksyen Pengurusan Sistem Maklumat','Information System Management Section',42,43,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (44,'Seksyen Pembangunan Kompetensi','Competency Development Section',42,41,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (45,'Seksyen Pengurusan Korporat','Corporate Management Section',42,42,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (46,'Seksyen Inovasi Dan Dokumentasi','Innovation and Documentation Section',42,40,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (47,'Seksyen Penyelarasan Pembangunan','Development Coordination Section',42,44,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (48,'Seksyen Perancangan Dan Dasar','Planning And Policy Section',42,45,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (49,'Bahagian Khidmat Pengurusan','Management Services Division',0,46,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (50,'Seksyen Sumber Manusia','Human Resources Section',49,49,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (51,'Seksyen Kewangan','Finance Section',49,47,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (52,'Seksyen Pentadbiran','Administration Section',49,48,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (53,'Bahagian Pemetaan Topografi Semenanjung','Peninsular Topography Mapping Division',0,50,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (54,'Pejabat Topografi Wilayah Taiping','Taiping Topographic Survey Regional Office',53,54,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (55,'Pejabat Topografi Wilayah Segamat','Segamat Topographic Survey Regional Office',53,53,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (56,'Pejabat Topografi Wilayah Kuantan','Kuantan Topographic Survey Regional Office',53,52,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (57,'Pejabat Topografi Wilayah Kuala Lumpur','Kuala Lumpur Topographic Survey Regional Office',53,51,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (58,'Seksyen Pangkalan Data Topografi','Topographic Database Section',53,56,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (59,'Seksyen Tadbir Urus dan Maklumat Geospatial','Administrative & Geospatial Information Section',53,57,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (60,'Seksyen Fotogrametri','Photogrammetry Section',53,55,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (61,'Bahagian Pemetaan Topografi Sabah','Sabah Topography Mapping Division',0,58,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (62,'Seksyen Pentadbiran Dan Maklumat Geospatial','Administration And Geospatial Information Section',61,63,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (63,'Seksyen Sempadan Dan Geodesi','Boundary And Geodetic Section',61,64,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (64,'Seksyen Penawanan Data','Data Acquisition Section',61,62,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (65,'Pejabat Topografi Wilayah Kota Kinabalu','Kota Kinabalu Topographic Survey Regional Office',61,59,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (66,'Pejabat Topografi Wilayah Tawau','Tawau Topographic Survey Regional Office',61,61,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (67,'Pejabat Topografi Wilayah Sandakan','Sandakan Topographic Survey Regional Office',61,60,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (68,'Bahagian Pemetaan Topografi Sarawak','Sarawak Topography Mapping Division',0,65,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (69,'Pejabat Topografi Wilayah Miri','Miri Topographic Survey Regional Office',68,69,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (70,'Cawangan Pengurusan Maklumat','Information Management Branch',68,66,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (71,'Seksyen Geodetik','Geodetic Section',68,71,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (72,'Seksyen Penawanan Data','Data Acquisition Section',68,73,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (73,'Pejabat Topografi Wilayah Sibu','Sibu Topographic Survey Regional Office',68,70,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (74,'Pejabat Topografi Wilayah Kuching','Kuching Topographic Survey Regional Office',68,68,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (75,'Cawangan Pentadbiran Dan Kewangan','Administration and Finance Branch',68,67,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (76,'Seksyen Pangkalan Data','Database Section',68,72,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (77,'JUPEM Negeri','JUPEM State',0,73,'hide');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (78,'JUPEM Perak','JUPEM Perak',0,80,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (79,'JUPEM Pahang','JUPEM Pahang',0,79,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (80,'JUPEM Johor','JUPEM Johor',0,74,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (81,'JUPEM Selangor','JUPEM Selangor',0,83,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (82,'JUPEM Kelantan','JUPEM Kelantan',0,76,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (83,'JUPEM Kedah','JUPEM Kedah',0,75,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (84,'JUPEM WP Labuan','JUPEM F.T. Labuan',0,86,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (85,'JUPEM WP Kuala Lumpur & Putrajaya','JUPEM F.T. Kuala Lumpur & Putrajaya',0,85,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (86,'JUPEM Negeri Sembilan','JUPEM Negeri Sembilan',0,78,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (87,'JUPEM Terengganu','JUPEM Terengganu',0,84,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (88,'JUPEM Perlis','JUPEM Perlis',0,81,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (89,'JUPEM Melaka','JUPEM Melaka',0,77,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (90,'JUPEM Pulau Pinang','JUPEM Penang',0,82,'show');
INSERT INTO `jabatan_units` (`id`,`name_my`,`name_en`,`parent_id`,`sort_order`,`status`) VALUES (91,'Seksyen Rundingan dan Keselamatan','Consulting and Security Section',13,16,'show');
